### PR TITLE
Update docker build, add instructions to README

### LINKED ISSUE #5: Update Docker image
I just  tried to run the server and encountered a few issues:
1. Readme  instructs to run  `pub get`  but there is no such command in flutter sdk (I am on Arch Linux, sdk version 3.16.5), maybe it should be `flutter pub get`?
2.  There is docker-compose.yml  file in this repo, but it is not described in readme, although it would be convenient just to run `docker-compose up` instead of  manually installing and configuring postgres and tudo server
3. `docker-compose up` is not working out of box, because it uses tudo_server image v35 that does not exists any more, maybe we would be better off using the most recent stable versions of postgres and tudo server instead (i.e. latest)?

### PR DESCRIPTION
**Pull request by bo0tzz**
Fixes #5, #6

### CODE REVIEW

**Review by cachapa — APPROVED** [review]

**Comment by cachapa** [comment]
Thank you!

**Comment by cachapa** [comment]
BTW, what happens on upgrades, does the Postgres database get wiped?

Would it make sense to have some light documentation on how to store the data appropriately?

**Comment by bo0tzz** [comment]
The postgres data is stored in a docker volume called `pgdata`. That keeps existing across updates, reboots, etc unless the user explicitly removes it. An alternative is to change `- pgdata:/var/lib/postgres/data` to use a mounted folder, like `- /some-folder:/var/lib/postgres/data`.

**Comment by cachapa** [comment]
Thanks for the clarification :+1:

**Pull request merged**
